Repository meilisearch/meilisearch-go, pull requests merged in 2023-03, with the labels that each got.

#417 Avoid panic when sending `(...[]string{})` in `AddDocument()`
  index_documents.go
Labels: bug, maintenance

#421 Update version for the next release (v0.23.1)
  version.go
Labels: skip-changelog

#422 Add multiple searches
  client.go
  client_test.go
  index_search.go
  types.go
  types_easyjson.go
Labels: enhancement
