Repository meilisearch/meilisearch-go, pull requests merged in 2023-10, with the labels that each got.

#493 Update code-samples
  .code-samples.meilisearch.yaml
Labels: documentation, skip-changelog

#495 Make `client.WaitForTask` use select and channels for polling
  client.go
Labels: enhancement

#492 feat!: enhanced enumeration for task types & statuses
  .code-samples.meilisearch.yaml
  client.go
  client_index_test.go
  client_test.go
  index.go
  index_documents_test.go
  index_test.go
  types.go
  types_easyjson.go
Labels: breaking-change
